### ISSUE TITLE
unify go-data json and go-wire json

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/go-data#2]
go-data json makes for nice apis and handles all the types that go-wire does. however, the json format is designed for readability and apis, rather than determinism.  in fact, setting the global `data.Encoder` will definitely lead to different results in different apps. This is fine for an exchange format, but not for anything that goes into app logic (the parsed json as a struct **is** deterministic)

Jae mentioned replacing the go-wire json with the go-data json, which I am not completely against, but we must first check where we rely on the determinism of go-wire json. A quick search in the codebase came up with at least 4 places, where go-wire JSON is used to build sign-bytes.  Which must be deterministic to reliably validate anything. These methods (at least) will need to find an alternative encoding if we modify the go-wire json style.

This is related to the following issue: https://github.com/tendermint/go-wire/issues/8

https://github.com/tendermint/tendermint/blob/master/types/vote.go#L59-L64
https://github.com/tendermint/tendermint/blob/master/types/proposal.go#L43-L48
https://github.com/tendermint/tendermint/blob/master/types/part_set.go#L76-L78
https://github.com/tendermint/tendermint/blob/master/types/block.go#L408-L415

Also see:
https://github.com/tendermint/tendermint/blob/master/types/canonical_json.go

**Comment by ethanfrey** [comment]
Okay, the rpc interface no longer uses go-wire json in `tendermint:develop`.

We still use this for canonical json generation, which we should revisit as well.

**Comment by zramsay** [comment]
Issue moved to [tendermint/go-wire #22](https://github.com/tendermint/go-wire/issues/22) via [**ZenHub**](https://www.zenhub.com/)
